name: SimpleBounty
version: '${project.version}'
main: xyz.iscarter.simplebounty.SimpleBounty
api-version: 1.19
authors: [ IsCarter ]
description: Allow players to set bountys on each other
depend:
  - "Vault"
softdepend:
  - PlaceholderAPI
commands:
  bounty:
    description: Bounty Command
  killpoint:
    description: Kill Points Command